//! `record`, `fuzz`, and `bench` command implementations for `tui-inject`.

use std::fs;
use std::panic;
use std::process::ExitCode;
use std::time::{Duration, Instant};

use crossterm::event::{Event, KeyCode, KeyEvent, KeyEventKind, KeyEventState, KeyModifiers};

use crate::widget::WidgetSpec;

// ============================================================
// record
// ============================================================

/// `tui-inject record` — capture keyboard events and save as TOML.
///
/// If the process has a controlling TTY, enters raw mode and records keys
/// interactively until `q` or `Ctrl+C` is pressed. If no TTY is available
/// (e.g. CI, piped stdin), writes a skeleton scenario file that the user
/// can edit.
pub fn record(output: &str) -> ExitCode {
    if !is_tty() {
        let toml = write_skeleton();
        match fs::write(output, toml) {
            Ok(()) => {
                eprintln!("no TTY detected — wrote skeleton scenario to {output}");
                eprintln!("edit it manually, then run `tui-inject replay {output}`");
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("write error: {e}");
                ExitCode::from(1)
            }
        }
    } else {
        record_interactive(output)
    }
}

/// Check if stdin is a TTY (best-effort, no extra dependency).
fn is_tty() -> bool {
    // We use crossterm's tty detection indirectly: try enable_raw_mode and
    // see if it succeeds. If it errors, we're not on a TTY.
    crossterm::terminal::enable_raw_mode().is_ok()
}

/// Build the skeleton scenario TOML content (without writing it).
fn write_skeleton() -> String {
    r#"# Skeleton scenario generated by `tui-inject record`.
# No controlling TTY was available, so this is a template — edit the events
# list manually, then run `tui-inject replay`.

[widget]
name = "counter"
initial = 0

# Events: each [[events]] block is one input.
# Simple form:
#   [[events]]
#   key = "enter"
#
# Modifier form:
#   [[events]]
#   key = "ctrl+c"
#
# Full form (with explicit modifiers list):
#   [[events]]
#   key = "a"
#   modifiers = ["shift"]

[[events]]
key = "+"

[[events]]
key = "+"

[[events]]
key = "q"

[output]
format = "text"
width = 40
height = 6
"#
    .to_string()
}

/// Interactive recording on a real TTY.
fn record_interactive(output: &str) -> ExitCode {
    use crossterm::event;
    use crossterm::event::{DisableMouseCapture, EnableMouseCapture};
    use crossterm::execute;
    use crossterm::terminal::{disable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen};
    use std::io::stdout;

    // Raw mode was enabled by is_tty(); set up the rest.
    let mut stdout = stdout();
    let _ = execute!(stdout, EnterAlternateScreen, EnableMouseCapture);

    let mut events: Vec<EventRecord> = Vec::new();
    let mut instructions = [
        "Recording — press keys to capture. Press q / Esc / Ctrl+C to stop.",
        "Each key will be saved as a [[events]] entry in the output TOML.",
    ];
    let _ = instructions.iter_mut(); // silence dead-code warning on instructions

    loop {
        if let Ok(true) = event::poll(Duration::from_millis(100)) {
            if let Ok(Event::Key(key)) = event::read() {
                if key.kind != KeyEventKind::Press {
                    continue;
                }
                let stop = matches!(key.code, KeyCode::Char('q') | KeyCode::Esc)
                    || (key.modifiers.contains(KeyModifiers::CONTROL)
                        && key.code == KeyCode::Char('c'));

                if !stop {
                    events.push(EventRecord::from(&key));
                }
                if stop {
                    break;
                }
            }
        }
    }

    let _ = execute!(stdout, LeaveAlternateScreen, DisableMouseCapture);
    let _ = disable_raw_mode();

    let toml = format_scenario_toml(&events);
    match fs::write(output, toml) {
        Ok(()) => {
            eprintln!("recorded {} events to {output}", events.len());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("write error: {e}");
            ExitCode::from(1)
        }
    }
}

/// Compact representation of one captured key event, for TOML output.
struct EventRecord {
    key: String,
    modifiers: Vec<String>,
}

impl EventRecord {
    fn from(key: &KeyEvent) -> Self {
        let key_str = match key.code {
            KeyCode::Enter => "enter".to_string(),
            KeyCode::Tab => "tab".to_string(),
            KeyCode::Backspace => "backspace".to_string(),
            KeyCode::Delete => "delete".to_string(),
            KeyCode::Esc => "esc".to_string(),
            KeyCode::Up => "up".to_string(),
            KeyCode::Down => "down".to_string(),
            KeyCode::Left => "left".to_string(),
            KeyCode::Right => "right".to_string(),
            KeyCode::Home => "home".to_string(),
            KeyCode::End => "end".to_string(),
            KeyCode::PageUp => "pageup".to_string(),
            KeyCode::PageDown => "pagedown".to_string(),
            KeyCode::Char(' ') => "space".to_string(),
            KeyCode::Char(c) => c.to_string(),
            KeyCode::F(n) => format!("f{n}"),
            KeyCode::Null => "null".to_string(),
            other => format!("{other:?}"),
        };
        let mut modifiers = Vec::new();
        if key.modifiers.contains(KeyModifiers::SHIFT) {
            modifiers.push("shift".to_string());
        }
        if key.modifiers.contains(KeyModifiers::CONTROL) {
            modifiers.push("ctrl".to_string());
        }
        if key.modifiers.contains(KeyModifiers::ALT) {
            modifiers.push("alt".to_string());
        }
        if key.modifiers.contains(KeyModifiers::SUPER) {
            modifiers.push("super".to_string());
        }
        Self {
            key: key_str,
            modifiers,
        }
    }
}

/// Format a list of captured events as a complete scenario TOML string.
fn format_scenario_toml(events: &[EventRecord]) -> String {
    let mut out = String::new();
    out.push_str("# Recorded with `tui-inject record`.\n\n");
    out.push_str("[widget]\nname = \"counter\"\ninitial = 0\n\n");
    for ev in events {
        if ev.modifiers.is_empty() {
            out.push_str(&format!("[[events]]\nkey = \"{}\"\n\n", ev.key));
        } else {
            let mods = ev
                .modifiers
                .iter()
                .map(|m| format!("\"{m}\""))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(
                "[[events]]\nkey = \"{}\"\nmodifiers = [{}]\n\n",
                ev.key, mods
            ));
        }
    }
    out.push_str("[output]\nformat = \"text\"\nwidth = 40\nheight = 6\n");
    out
}

// ============================================================
// fuzz
// ============================================================

/// `tui-inject fuzz <widget> --events N` — inject N random events.
///
/// Drives a Counter App through N random key events, using `catch_unwind`
/// per event to isolate panics. Reports total events, panics, and final state.
pub fn fuzz(name: &str, event_count: usize) -> ExitCode {
    if name != "counter" {
        eprintln!("fuzz: widget '{name}' not supported (only 'counter' is fuzzable currently)");
        return ExitCode::from(2);
    }

    let mut rng = Prng::seeded(0xC0FFEE_u64);
    let mut panics = 0;
    let mut counter = CounterForFuzz::default();

    for i in 0..event_count {
        let event = random_key_event(&mut rng);
        let result = panic::catch_unwind(panic::AssertUnwindSafe(|| {
            counter.on_event(event);
        }));
        if result.is_err() {
            panics += 1;
            eprintln!("fuzz: panic at event {i}");
        }
    }

    println!("fuzz results for '{name}':");
    println!("  events generated: {event_count}");
    println!("  panics:           {panics}");
    println!("  final count:      {}", counter.count);
    if panics == 0 {
        println!("  status:           OK (no panics)");
        ExitCode::SUCCESS
    } else {
        println!("  status:           FAIL ({panics} panics)");
        ExitCode::from(1)
    }
}

/// Minimal xorshift PRNG — no external dependency.
struct Prng {
    state: u64,
}

impl Prng {
    fn seeded(seed: u64) -> Self {
        Self {
            state: if seed == 0 { 0xDEADBEEF } else { seed },
        }
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        let idx = (self.next_u64() as usize) % items.len();
        &items[idx]
    }
}

/// Generate a random key event from a small, known-safe alphabet.
fn random_key_event(rng: &mut Prng) -> Event {
    let codes = [
        KeyCode::Char('+'),
        KeyCode::Char('-'),
        KeyCode::Up,
        KeyCode::Down,
        KeyCode::Char('r'),
        KeyCode::Char('q'),
        KeyCode::Esc,
        KeyCode::Enter,
        KeyCode::Tab,
        KeyCode::Char('a'),
    ];
    Event::Key(KeyEvent::new_with_kind_and_state(
        *rng.pick(&codes),
        KeyModifiers::NONE,
        KeyEventKind::Press,
        KeyEventState::NONE,
    ))
}

/// Minimal Counter for fuzzing — stateful, with the same Msg logic as the
/// demo app, but without the App/Model trait baggage (no Command plumbing).
#[derive(Debug, Default)]
struct CounterForFuzz {
    count: i32,
}

impl CounterForFuzz {
    fn on_event(&mut self, event: Event) {
        if let Event::Key(KeyEvent {
            code,
            kind: KeyEventKind::Press,
            ..
        }) = event
        {
            match code {
                KeyCode::Char('+') | KeyCode::Up => self.count += 1,
                KeyCode::Char('-') | KeyCode::Down => self.count -= 1,
                KeyCode::Char('r') => self.count = 0,
                _ => {}
            }
        }
    }
}

// ============================================================
// bench
// ============================================================

/// `tui-inject bench <widget> --iterations N` — measure render time.
///
/// Renders the widget N times via TestBackend and reports min/mean/p95/max.
pub fn bench(name: &str, iterations: usize) -> ExitCode {
    let spec = match WidgetSpec::from_name(name) {
        Some(s) => s,
        None => {
            eprintln!(
                "bench: unknown widget '{name}'. Available: {}",
                WidgetSpec::NAMES.join(", ")
            );
            return ExitCode::from(1);
        }
    };

    let width = 60_u16;
    let height = 16_u16;
    let mut timings: Vec<Duration> = Vec::with_capacity(iterations);

    for _ in 0..iterations {
        let backend = ratatui::backend::TestBackend::new(width, height);
        let mut terminal = ratatui::Terminal::new(backend).expect("terminal");
        let start = Instant::now();
        terminal
            .draw(|frame| spec.render(frame, ratatui::layout::Rect::new(0, 0, width, height)))
            .expect("draw");
        timings.push(start.elapsed());
    }

    timings.sort();
    let min = timings.first().copied().unwrap_or_default();
    let max = timings.last().copied().unwrap_or_default();
    let mean_ns = timings.iter().map(|d| d.as_nanos()).sum::<u128>() / iterations.max(1) as u128;
    let p95_idx = (iterations * 95) / 100;
    let p95 = timings
        .get(p95_idx.min(timings.len().saturating_sub(1)))
        .copied()
        .unwrap_or_default();

    println!("bench results for '{name}' ({iterations} iterations, {width}x{height}):");
    println!("  min:  {}", format_duration(min));
    println!(
        "  mean: {}",
        format_duration(Duration::from_nanos(mean_ns as u64))
    );
    println!("  p95:  {}", format_duration(p95));
    println!("  max:  {}", format_duration(max));
    ExitCode::SUCCESS
}

/// Format a Duration for human-friendly display.
fn format_duration(d: Duration) -> String {
    let ns = d.as_nanos();
    if ns < 1_000 {
        format!("{ns} ns")
    } else if ns < 1_000_000 {
        format!("{:.2} µs", ns as f64 / 1_000.0)
    } else {
        format!("{:.2} ms", ns as f64 / 1_000_000.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prng_is_deterministic() {
        let mut a = Prng::seeded(42);
        let mut b = Prng::seeded(42);
        for _ in 0..10 {
            assert_eq!(a.next_u64(), b.next_u64());
        }
    }

    #[test]
    fn prng_pick_returns_in_range() {
        let mut rng = Prng::seeded(7);
        let items = [1, 2, 3, 4, 5];
        for _ in 0..20 {
            let picked = rng.pick(&items);
            assert!(items.contains(picked));
        }
    }

    #[test]
    fn random_key_event_produces_known_codes() {
        let mut rng = Prng::seeded(99);
        for _ in 0..20 {
            let ev = random_key_event(&mut rng);
            assert!(matches!(ev, Event::Key(_)));
        }
    }

    #[test]
    fn counter_for_fuzz_increments_and_decrements() {
        let mut c = CounterForFuzz::default();
        c.on_event(random_key_event(&mut Prng::seeded(1)));
        // Just verify it doesn't panic on any random event.
        let mut rng = Prng::seeded(2);
        for _ in 0..100 {
            c.on_event(random_key_event(&mut rng));
        }
    }

    #[test]
    fn format_duration_handles_ranges() {
        assert_eq!(format_duration(Duration::from_nanos(500)), "500 ns");
        assert_eq!(format_duration(Duration::from_nanos(1_500)), "1.50 µs");
        assert_eq!(format_duration(Duration::from_nanos(1_500_000)), "1.50 ms");
    }

    #[test]
    fn format_scenario_toml_includes_widget_and_output() {
        let events = vec![EventRecord {
            key: "enter".to_string(),
            modifiers: vec![],
        }];
        let toml = format_scenario_toml(&events);
        assert!(toml.contains("[widget]"));
        assert!(toml.contains("[[events]]"));
        assert!(toml.contains("[output]"));
        assert!(toml.contains("enter"));
    }

    #[test]
    fn event_record_maps_chars_and_arrows() {
        let key = KeyEvent::new_with_kind_and_state(
            KeyCode::Char('a'),
            KeyModifiers::SHIFT,
            KeyEventKind::Press,
            KeyEventState::NONE,
        );
        let rec = EventRecord::from(&key);
        assert_eq!(rec.key, "a");
        assert_eq!(rec.modifiers, vec!["shift".to_string()]);

        let key = KeyEvent::new_with_kind_and_state(
            KeyCode::Up,
            KeyModifiers::NONE,
            KeyEventKind::Press,
            KeyEventState::NONE,
        );
        let rec = EventRecord::from(&key);
        assert_eq!(rec.key, "up");
        assert!(rec.modifiers.is_empty());
    }

    #[test]
    fn write_skeleton_includes_counter_widget() {
        let toml = write_skeleton();
        assert!(toml.contains("name = \"counter\""));
        assert!(toml.contains("[[events]]"));
    }
}
